arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  constraints:
      goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0

      joint1: {trajectory: 0.1, goal: 0.1}
      joint2: {trajectory: 0.1, goal: 0.1}
      joint3: {trajectory: 0.1, goal: 0.1}
      joint4: {trajectory: 0.1, goal: 0.1}
  gain:
      joint1: {p: 100, d: 1, i: 1, i_clamp: 1}
      joint2: {p: 100, d: 1, i: 1, i_clamp: 1}
      joint3: {p: 100, d: 1, i: 1, i_clamp: 1}
      joint4: {p: 100, d: 1, i: 1, i_clamp: 1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10